site_name: HypIgu Documentation
nav:
    - Home: index.md
    - Constructors: constructors.md
    - Lattices: lattices.md
    - Generating Functions: generating-functions.md
theme:
    name: mkdocs
    custom_dir: custom_theme/